apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: doodle-world-ruby
    app.kubernetes.io/instance: world-ruby-xyzz
    app.kubernetes.io/version: "0.9.1"
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: helloworld
    app.kubernetes.io/managed-by: kubectl
  name: doodle-world-ruby
  namespace: supreme-doodle
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: doodle-world-ruby
      app.kubernetes.io/instance: world-ruby-xyzz
      app.kubernetes.io/version: "0.9.1"
      app.kubernetes.io/component: service
      app.kubernetes.io/part-of: helloworld
      app.kubernetes.io/managed-by: kubectl
  template:
    metadata:
      labels:
        ruby:
        app.kubernetes.io/name: doodle-world-ruby
        app.kubernetes.io/instance: world-ruby-xyzz
        app.kubernetes.io/version: "0.9.1"
        app.kubernetes.io/component: service
        app.kubernetes.io/part-of: helloworld
        app.kubernetes.io/managed-by: kubectl
    spec:
      containers:
      - name: doodle-world-ruby
        image: ghcr.io/scrogatl/doodle-world-ruby:main
        imagePullPolicy: Always
        command: ["bundle", "exec", "rackup", "--host", "0.0.0.0", "-p", "5003"]
        env:
        - name: SHARD
          value: "blue"
        ports:
        - containerPort: 5003
          name: application
          protocol: TCP
