apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: helloworld
    service: doodle-weather
    version: blue
    shard: blue
  name: weather
  namespace: supreme-doodle
spec:
  replicas: 1
  selector:
    matchLabels:
      application: helloworld
      service: doodle-weather
      version: blue
      shard: blue
  template:
    metadata:
      labels:
        application: helloworld
        service: doodle-weather
        version: blue
        shard: blue
    spec:
      containers:
      - name: weather
        image: ghcr.io/scrogatl/doodle-weather:main
        imagePullPolicy: Always
        env:
        - name: SHARD
          value: "blue"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: NEW_RELIC_LICENSE_KEY
          value:  "{{ .Values.nr_key }}"
        ports:
        - containerPort: 5100
          name: application
          protocol: TCP
