apiVersion: apps/v1
kind: Deployment
metadata:
  name: doodle-frontend
  namespace: supreme-doodle
  labels:
    app.kubernetes.io/name: doodle-frontend
    app.kubernetes.io/instance: frontend-instance
    app.kubernetes.io/version: "0.9.1"
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: helloworld
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: doodle-frontend
      app.kubernetes.io/instance: frontend-instance
      app.kubernetes.io/version: "0.9.1"
      app.kubernetes.io/component: service
      app.kubernetes.io/part-of: helloworld
      app.kubernetes.io/managed-by: kubectl
  template:
    metadata:
      labels:
        app.kubernetes.io/name: doodle-frontend
        app.kubernetes.io/instance: frontend-instance
        app.kubernetes.io/version: "0.9.1"
        app.kubernetes.io/component: service
        app.kubernetes.io/part-of: helloworld
        app.kubernetes.io/managed-by: kubectl
    spec:
      containers:
      - name: doodle-frontend
        image: ghcr.io/scrogatl/doodle-frontend:otel
        imagePullPolicy: Always
        command: ["opentelemetry-instrument", "flask", "run", "--host=0.0.0.0", "-p 5000"]
        env:
        - name: HELLO_HOST
          value: "doodle-hello"
        - name: WORLD_HOST
          value: "doodle-world"
        - name: WORLD_HOST_RUBY
          value: "doodle-world-ruby"
        - name: WPORT
          value: "5002"
        - name: WPORT_RUBY
          value: "5003"
        - name: SHARD
          value: "blue"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: RUBY_WORLD
          value: "50"
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: nr-license-key  # The name of your K8s Secret
              key: license-key      # The key inside the Secret
        - name: OTEL_SERVICE_NAME
          value: "frontend-otel"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "https://otlp.nr-data.net"
        - name: OTEL_EXPORTER_OTLP_HEADERS
          value: "api-key=$(NEW_RELIC_LICENSE_KEY)"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
          value: "true"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
        - name: OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT
          value: "4095"
        - name: OTEL_EXPORTER_OTLP_COMPRESSION
          value: "gzip"

        ports:
        - containerPort: 5000
          name: application
          protocol: TCP
